<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/NeoAstra/NeoAstra.csproj" />
    <None
      Include="capabilities/*.json"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
      Link="capabilities/%(Filename)%(Extension)" />
  </ItemGroup>

  <Import Project="../../src/NeoAstra/Build/Sdk/NeoAstra.props" />
  <Import Project="../../src/NeoAstra/Build/Sdk/NeoAstra.Build.targets" />
</Project>
