<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeoAstra\NeoAstra.csproj" />
    <ProjectReference Include="..\NeoAstra.SingleInstanceHelper\NeoAstra.SingleInstanceHelper.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\NeoAstra.Generator\NeoAstra.Generator.csproj" />
    <ProjectReference Include="..\NeoAstra.Tooling\NeoAstra.Tooling.csproj" />
    <ProjectReference Include="..\NeoAstra.Tool\NeoAstra.Tool.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\NeoAstra.Capabilities.Tool\NeoAstra.Capabilities.Tool.csproj" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
