#ifndef NEOASTRA_VERSION_H
#define NEOASTRA_VERSION_H

#define NEOASTRA_VERSION_MAJOR 0
#define NEOASTRA_VERSION_MINOR 1
#define NEOASTRA_VERSION_PATCH 0
#define NEOASTRA_ABI_VERSION_MAJOR 1
#define NEOASTRA_ABI_VERSION_MINOR 8

#endif
