#ifndef NEOWEBVIEW_VERSION_H
#define NEOWEBVIEW_VERSION_H

#define NEO_WEBVIEW_VERSION_MAJOR 0
#define NEO_WEBVIEW_VERSION_MINOR 1
#define NEO_WEBVIEW_VERSION_PATCH 0
#define NEO_WEBVIEW_ABI_VERSION_MAJOR 1
#define NEO_WEBVIEW_ABI_VERSION_MINOR 5

#endif
