<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <NeoRpcTypeScriptOutput>$(MSBuildProjectDirectory)/ClientApp/src/generated/neoastra.ts</NeoRpcTypeScriptOutput>
    <NeoRpcJavaScriptOutput>$(MSBuildProjectDirectory)/assets/generated/neoastra.js</NeoRpcJavaScriptOutput>
    <NeoRpcJavaScriptImport>../neoastra-client/index.js</NeoRpcJavaScriptImport>
    <NeoRpcManifestOutput>$(MSBuildProjectDirectory)/obj/generated/neoastra.manifest.json</NeoRpcManifestOutput>
    <NeoRpcSchemaOutput>$(MSBuildProjectDirectory)/obj/generated/neoastra.schema.json</NeoRpcSchemaOutput>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="NeoRpcTypeScriptOutput" />
    <CompilerVisibleProperty Include="NeoRpcJavaScriptOutput" />
    <CompilerVisibleProperty Include="NeoRpcJavaScriptImport" />
    <CompilerVisibleProperty Include="NeoRpcManifestOutput" />
    <CompilerVisibleProperty Include="NeoRpcSchemaOutput" />
    <ProjectReference Include="../../src/NeoAstra/NeoAstra.csproj" />
    <None Include="assets/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
