<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NeoAstra/NeoAstra.csproj" />
    <Content Include="assets/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
