#include "../common/native_internal.hpp"

#include <gtk/gtk.h>
#include <webkit2/webkit2.h>

#include <algorithm>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace {
struct gtk_app { GMainContext* context{}; };
struct gtk_window { GtkWidget* widget{}; };
struct gtk_environment { WebKitWebContext* context{}; };
struct gtk_profile { WebKitWebContext* context{}; };
struct gtk_view { GtkWidget* widget{}; WebKitUserContentManager* content{}; gulong load_changed{}; gulong load_failed{}; gulong title_changed{}; gulong uri_changed{}; gulong message_received{}; uint64_t next_script{1}; std::unordered_map<std::string,WebKitUserScript*> scripts; };

neo_webview_error_t* make_error(neo_webview_result_t code, const char* message, int64_t native_code = 0, const char* domain = "webkitgtk") noexcept { neo_webview_error_t* error{}; neo_fail(&error, code, message, native_code, domain); return error; }

GtkWidget* view_parent(neo_webview_view_t* view) noexcept {
    if (view->window) { auto* state=static_cast<gtk_window*>(view->window->platform); return state?state->widget:nullptr; }
    return view->parent.kind==NEO_WEBVIEW_NATIVE_PARENT_GTK_WIDGET?static_cast<GtkWidget*>(view->parent.handle):nullptr;
}

void NEO_WEBVIEW_CALL invoke_dispatch(void* data) { auto* app=static_cast<neo_webview_app_t*>(data); neo_drain_dispatch(app); app->release(); }
gboolean dispatch_on_main(void* data) { invoke_dispatch(data); return G_SOURCE_REMOVE; }

void window_destroyed(GtkWidget*, void* data) { auto* window=static_cast<neo_webview_window_t*>(data); auto* state=static_cast<gtk_window*>(window->platform); if(state)state->widget=nullptr; neo_window_closed(window); }
gboolean window_delete(GtkWidget*, GdkEvent*, void* data) { auto* window=static_cast<neo_webview_window_t*>(data); neo_emit_app(window->app,NEO_WEBVIEW_EVENT_WINDOW_CLOSE_REQUESTED,window->id); return FALSE; }
void window_size(GtkWidget*, GdkRectangle* allocation, void* data) { auto* window=static_cast<neo_webview_window_t*>(data); {std::lock_guard lock(window->state_mutex);window->bounds.width=allocation->width;window->bounds.height=allocation->height;} neo_emit_app(window->app,NEO_WEBVIEW_EVENT_WINDOW_RESIZED,window->id); }

struct navigation_context { WebKitPolicyDecision* policy{}; };
void navigation_decided(void* pointer, neo_webview_decision_action_t action) noexcept { std::unique_ptr<navigation_context> context(static_cast<navigation_context*>(pointer)); if(action==NEO_WEBVIEW_DECISION_ALLOW)webkit_policy_decision_use(context->policy);else webkit_policy_decision_ignore(context->policy);g_object_unref(context->policy); }
gboolean decide_policy(WebKitWebView*, WebKitPolicyDecision* policy, WebKitPolicyDecisionType type, void* data) {
    if(type!=WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION)return FALSE;
    auto* view=static_cast<neo_webview_view_t*>(data);
    auto* navigation=WEBKIT_NAVIGATION_POLICY_DECISION(policy);
    auto* action=webkit_navigation_policy_decision_get_navigation_action(navigation);
    auto* request=webkit_navigation_action_get_request(action);
    std::string uri=webkit_uri_request_get_uri(request)?webkit_uri_request_get_uri(request):"";
    auto* decision=new neo_webview_decision;
    decision->kind=NEO_WEBVIEW_DECISION_NAVIGATION;decision->default_action=NEO_WEBVIEW_DECISION_ALLOW;
    auto* context=new navigation_context{WEBKIT_POLICY_DECISION(g_object_ref(policy))};decision->completion=navigation_decided;decision->completion_context=context;
    const auto navigation_type=webkit_navigation_action_get_navigation_type(action);
    const uint64_t flags=1u|((navigation_type==WEBKIT_NAVIGATION_TYPE_LINK_CLICKED)?2u:0u);
    neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_REQUESTED,0,nullptr,&uri,flags,0,decision);
    if(decision->state.load()==neo_decision_state::pending){neo_webview_decision_response_t response{sizeof(response),1,NEO_WEBVIEW_DECISION_DEFAULT};neo_webview_decision_complete(decision,&response,nullptr);}
    decision->release();return TRUE;
}
void load_changed(WebKitWebView* webview, WebKitLoadEvent event, void* data) { auto* view=static_cast<neo_webview_view_t*>(data);const char* raw=webkit_web_view_get_uri(webview);std::string uri=raw?raw:"";if(event==WEBKIT_LOAD_STARTED)neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_STARTED,0,nullptr,&uri,1);else if(event==WEBKIT_LOAD_FINISHED)neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_COMPLETED,0,nullptr,&uri); }
gboolean load_failed(WebKitWebView*, WebKitLoadEvent, const char* uri, GError* error, void* data) { auto* view=static_cast<neo_webview_view_t*>(data);std::string value=uri?uri:"";neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_FAILED,0,nullptr,&value,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,error?error->code:0);return FALSE; }
void title_changed(GObject* object,GParamSpec*,void* data){auto* view=static_cast<neo_webview_view_t*>(data);const auto* value=webkit_web_view_get_title(WEBKIT_WEB_VIEW(object));view->title=value?value:"";neo_emit_view(view,NEO_WEBVIEW_EVENT_TITLE_CHANGED,0,&view->title);}
void uri_changed(GObject* object,GParamSpec*,void* data){auto* view=static_cast<neo_webview_view_t*>(data);const auto* value=webkit_web_view_get_uri(WEBKIT_WEB_VIEW(object));view->source=value?value:"";neo_emit_view(view,NEO_WEBVIEW_EVENT_SOURCE_CHANGED,0,nullptr,&view->source);}
void message_received(WebKitUserContentManager*,WebKitJavascriptResult* result,void* data){auto* view=static_cast<neo_webview_view_t*>(data);auto* value=webkit_javascript_result_get_js_value(result);char* json=jsc_value_to_json(value,0);std::string message=json?json:"null";g_free(json);neo_emit_view(view,NEO_WEBVIEW_EVENT_MESSAGE_RECEIVED,0,&message,nullptr,1);}

struct script_context { neo_webview_view_t* view{};neo_webview_string_callback_t callback{};void* context{};neo_webview_operation_t* operation{}; };
void script_finished(GObject* object,GAsyncResult* result,void* data){std::unique_ptr<script_context> context(static_cast<script_context*>(data));GError* error{};auto* value=webkit_web_view_evaluate_javascript_finish(WEBKIT_WEB_VIEW(object),result,&error);std::string output;neo_webview_error_t* native_error{};auto requested=NEO_WEBVIEW_OK;if(error){requested=NEO_WEBVIEW_ERROR_NATIVE_FAILURE;native_error=make_error(requested,error->message,error->code);g_error_free(error);}else if(value){char* json=jsc_value_to_json(value,0);output=json?json:"null";g_free(json);g_object_unref(value);}neo_webview_result_t actual{};if(context->operation->try_complete(requested,actual))context->callback(context->context,actual,actual==NEO_WEBVIEW_OK?neo_string_view(output):neo_webview_string_view_t{},native_error);if(native_error)native_error->release();context->operation->release();}
struct add_script_context { neo_webview_string_callback_t callback{};void* context{};neo_webview_operation_t* operation{};std::string identifier; };
gboolean script_added(void* data){std::unique_ptr<add_script_context> completion(static_cast<add_script_context*>(data));neo_webview_result_t actual{};if(completion->operation->try_complete(NEO_WEBVIEW_OK,actual))completion->callback(completion->context,actual,actual==NEO_WEBVIEW_OK?neo_string_view(completion->identifier):neo_webview_string_view_t{},nullptr);completion->operation->release();return G_SOURCE_REMOVE;}

void append_json_string(std::string& output,const char* value){output.push_back('"');for(const auto* current=reinterpret_cast<const unsigned char*>(value?value:"");*current;++current){switch(*current){case '"':output+="\\\"";break;case '\\':output+="\\\\";break;case '\b':output+="\\b";break;case '\f':output+="\\f";break;case '\n':output+="\\n";break;case '\r':output+="\\r";break;case '\t':output+="\\t";break;default:if(*current<0x20){char escape[7]{};g_snprintf(escape,sizeof(escape),"\\u%04x",*current);output+=escape;}else output.push_back(static_cast<char>(*current));break;}}output.push_back('"');}
struct cookie_context { neo_webview_buffer_callback_t callback{};void* context{};neo_webview_operation_t* operation{}; };
void cookies_finished(GObject* object,GAsyncResult* result,void* data){std::unique_ptr<cookie_context> completion(static_cast<cookie_context*>(data));GError* error{};GList* cookies=webkit_cookie_manager_get_cookies_finish(WEBKIT_COOKIE_MANAGER(object),result,&error);neo_webview_result_t requested=error?NEO_WEBVIEW_ERROR_NATIVE_FAILURE:NEO_WEBVIEW_OK,actual{};neo_webview_error_t* native_error=error?make_error(requested,error->message,error->code):nullptr;std::string json="[";uint32_t index{};if(!error){for(auto* item=cookies;item;item=item->next){auto* cookie=static_cast<SoupCookie*>(item->data);if(index++)json.push_back(',');json+="{\"name\":";append_json_string(json,soup_cookie_get_name(cookie));json+=",\"value\":";append_json_string(json,soup_cookie_get_value(cookie));json+=",\"domain\":";append_json_string(json,soup_cookie_get_domain(cookie));json+=",\"path\":";append_json_string(json,soup_cookie_get_path(cookie));json+=",\"secure\":";json+=soup_cookie_get_secure(cookie)?"true":"false";json+=",\"httpOnly\":";json+=soup_cookie_get_http_only(cookie)?"true":"false";json+=",\"sameSite\":"+std::to_string(static_cast<uint32_t>(soup_cookie_get_same_site_policy(cookie))+1u);if(auto* expires=soup_cookie_get_expires(cookie))json+=",\"expiresUnixMs\":"+std::to_string(g_date_time_to_unix(expires)*1000);json.push_back('}');}json.push_back(']');}auto* buffer=error?nullptr:new neo_webview_buffer(std::vector<uint8_t>(json.begin(),json.end()));if(completion->operation->try_complete(requested,actual)){completion->callback(completion->context,actual,actual==NEO_WEBVIEW_OK?buffer:nullptr,actual==requested?native_error:nullptr);if(actual!=NEO_WEBVIEW_OK&&buffer)buffer->release();}else if(buffer)buffer->release();if(cookies)g_list_free_full(cookies,reinterpret_cast<GDestroyNotify>(soup_cookie_free));if(error)g_error_free(error);if(native_error)native_error->release();completion->operation->release();}
struct cookie_change_context { neo_webview_completion_callback_t callback{};void* context{};neo_webview_operation_t* operation{};bool deleting{}; };
void cookie_changed(GObject* object,GAsyncResult* result,void* data){std::unique_ptr<cookie_change_context> completion(static_cast<cookie_change_context*>(data));GError* error{};gboolean success=completion->deleting?webkit_cookie_manager_delete_cookie_finish(WEBKIT_COOKIE_MANAGER(object),result,&error):webkit_cookie_manager_add_cookie_finish(WEBKIT_COOKIE_MANAGER(object),result,&error);auto requested=success?NEO_WEBVIEW_OK:NEO_WEBVIEW_ERROR_NATIVE_FAILURE;neo_webview_error_t* native_error=error?make_error(requested,error->message,error->code):nullptr;neo_webview_result_t actual{};if(completion->operation->try_complete(requested,actual))completion->callback(completion->context,actual,actual==requested?native_error:nullptr);if(error)g_error_free(error);if(native_error)native_error->release();completion->operation->release();}
SoupCookie* make_cookie(const neo_webview_cookie_t* value){const auto name=neo_string(value->name),text=neo_string(value->value),domain=neo_string(value->domain),path=neo_string(value->path);auto* cookie=soup_cookie_new(name.c_str(),text.c_str(),domain.c_str(),path.c_str(),-1);if(!cookie)return nullptr;soup_cookie_set_secure(cookie,(value->flags&1u)!=0);soup_cookie_set_http_only(cookie,(value->flags&2u)!=0);if(value->same_site>0)soup_cookie_set_same_site_policy(cookie,static_cast<SoupSameSitePolicy>(value->same_site-1u));if((value->flags&4u)==0&&value->expires_unix_ms>0){auto* expires=g_date_time_new_from_unix_utc(value->expires_unix_ms/1000);soup_cookie_set_expires(cookie,expires);g_date_time_unref(expires);}return cookie;}
struct clear_context { neo_webview_completion_callback_t callback{};void* context{};neo_webview_operation_t* operation{}; };
void clear_finished(GObject* object,GAsyncResult* result,void* data){std::unique_ptr<clear_context> completion(static_cast<clear_context*>(data));GError* error{};const auto success=webkit_website_data_manager_clear_finish(WEBKIT_WEBSITE_DATA_MANAGER(object),result,&error);const auto requested=success?NEO_WEBVIEW_OK:NEO_WEBVIEW_ERROR_NATIVE_FAILURE;neo_webview_error_t* native_error=error?make_error(requested,error->message,error->code):nullptr;neo_webview_result_t actual{};if(completion->operation->try_complete(requested,actual))completion->callback(completion->context,actual,actual==requested?native_error:nullptr);if(error)g_error_free(error);if(native_error)native_error->release();completion->operation->release();}
}

bool neo_platform_initialize(neo_webview_app_t* app,neo_webview_error_t** error) noexcept {if(!gtk_init_check(nullptr,nullptr)){neo_fail(error,NEO_WEBVIEW_ERROR_BACKEND_UNAVAILABLE,"GTK could not connect to a display",0,"gtk");return false;}auto* state=new(std::nothrow) gtk_app;if(!state){neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"GTK backend allocation failed");return false;}state->context=g_main_context_ref_thread_default();app->platform=state;return true;}
void neo_platform_shutdown(neo_webview_app_t* app) noexcept {auto* state=static_cast<gtk_app*>(app->platform);if(!state)return;if(state->context)g_main_context_unref(state->context);delete state;app->platform=nullptr;}
int32_t neo_platform_run(neo_webview_app_t* app) noexcept {gtk_main();return app->exit_code.load();}
void neo_platform_quit(neo_webview_app_t*) noexcept {auto* source=g_idle_source_new();g_source_set_callback(source,[](void*)->gboolean{gtk_main_quit();return G_SOURCE_REMOVE;},nullptr,nullptr);g_source_attach(source,nullptr);g_source_unref(source);}
void neo_platform_wake(neo_webview_app_t* app) noexcept {auto* state=static_cast<gtk_app*>(app->platform);if(!state||!state->context)return;app->retain();auto* source=g_idle_source_new();g_source_set_callback(source,dispatch_on_main,app,nullptr);g_source_attach(source,state->context);g_source_unref(source);}

bool neo_platform_window_create(neo_webview_window_t* window,const neo_webview_window_options_t* options,neo_webview_error_t**) noexcept {auto* state=new(std::nothrow) gtk_window;if(!state)return false;state->widget=gtk_window_new(GTK_WINDOW_TOPLEVEL);window->platform=state;gtk_window_set_title(GTK_WINDOW(state->widget),window->title.c_str());gtk_window_move(GTK_WINDOW(state->widget),window->bounds.x,window->bounds.y);gtk_window_set_default_size(GTK_WINDOW(state->widget),window->bounds.width,window->bounds.height);GdkGeometry geometry{};GdkWindowHints hints=(GdkWindowHints)0;if(options->minimum_size.width>0||options->minimum_size.height>0){geometry.min_width=std::max(options->minimum_size.width,1);geometry.min_height=std::max(options->minimum_size.height,1);hints=(GdkWindowHints)(hints|GDK_HINT_MIN_SIZE);}if(options->maximum_size.width>0||options->maximum_size.height>0){geometry.max_width=options->maximum_size.width>0?options->maximum_size.width:G_MAXINT;geometry.max_height=options->maximum_size.height>0?options->maximum_size.height:G_MAXINT;hints=(GdkWindowHints)(hints|GDK_HINT_MAX_SIZE);}if(hints)gtk_window_set_geometry_hints(GTK_WINDOW(state->widget),nullptr,&geometry,hints);gtk_window_set_resizable(GTK_WINDOW(state->widget),(options->flags&1u)!=0);gtk_window_set_decorated(GTK_WINDOW(state->widget),(options->flags&2u)!=0);gtk_window_set_keep_above(GTK_WINDOW(state->widget),(options->flags&8u)!=0);gtk_window_set_skip_taskbar_hint(GTK_WINDOW(state->widget),(options->flags&16u)==0);if(window->owner){auto* owner=static_cast<gtk_window*>(window->owner->platform);if(owner&&owner->widget)gtk_window_set_transient_for(GTK_WINDOW(state->widget),GTK_WINDOW(owner->widget));}g_signal_connect(state->widget,"delete-event",G_CALLBACK(window_delete),window);g_signal_connect(state->widget,"destroy",G_CALLBACK(window_destroyed),window);g_signal_connect(state->widget,"size-allocate",G_CALLBACK(window_size),window);if(options->flags&4u){gtk_widget_show_all(state->widget);if(options->state==NEO_WEBVIEW_WINDOW_MINIMIZED)gtk_window_iconify(GTK_WINDOW(state->widget));else if(options->state==NEO_WEBVIEW_WINDOW_MAXIMIZED)gtk_window_maximize(GTK_WINDOW(state->widget));}return true;}
void neo_platform_window_destroy(neo_webview_window_t* window) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state)return;if(state->widget)gtk_widget_destroy(state->widget);delete state;window->platform=nullptr;}
neo_webview_result_t neo_platform_window_show(neo_webview_window_t* window,bool visible) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;if(visible)gtk_widget_show_all(state->widget);else gtk_widget_hide(state->widget);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_activate(neo_webview_window_t* window) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;gtk_window_present(GTK_WINDOW(state->widget));return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_close(neo_webview_window_t* window) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;gtk_widget_destroy(state->widget);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_title(neo_webview_window_t* window) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;gtk_window_set_title(GTK_WINDOW(state->widget),window->title.c_str());return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_bounds(neo_webview_window_t* window) noexcept {auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;gtk_window_move(GTK_WINDOW(state->widget),window->bounds.x,window->bounds.y);gtk_window_resize(GTK_WINDOW(state->widget),window->bounds.width,window->bounds.height);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_get_handle(neo_webview_window_t* window,neo_webview_native_handle_kind_t kind,neo_webview_native_handle_t* handle) noexcept {if(kind!=NEO_WEBVIEW_NATIVE_HANDLE_GTK_WIDGET)return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;auto* state=static_cast<gtk_window*>(window->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_DISPOSED;handle->kind=kind;handle->value=state->widget;return NEO_WEBVIEW_OK;}

bool neo_platform_environment_create_async(neo_webview_environment_t* environment,const neo_webview_environment_options_t* options,neo_platform_created_callback_t callback,void* context,neo_webview_error_t**) noexcept {auto* state=new(std::nothrow) gtk_environment;if(!state)return false;state->context=options->private_mode?webkit_web_context_new_ephemeral():webkit_web_context_new();environment->platform=state;if(!state->context){delete state;environment->platform=nullptr;return false;}callback(context,nullptr);return true;}
void neo_platform_environment_destroy(neo_webview_environment_t* environment) noexcept {auto* state=static_cast<gtk_environment*>(environment->platform);if(!state)return;if(state->context)g_object_unref(state->context);delete state;environment->platform=nullptr;}
bool neo_platform_profile_create(neo_webview_profile_t* profile,neo_webview_error_t** error) noexcept {auto* state=new(std::nothrow) gtk_profile;if(!state){neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK profile allocation failed");return false;}auto* environment=static_cast<gtk_environment*>(profile->environment->platform);state->context=profile->ephemeral?webkit_web_context_new_ephemeral():environment&&environment->context?WEBKIT_WEB_CONTEXT(g_object_ref(environment->context)):nullptr;if(!state->context){delete state;neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK profile context creation failed");return false;}profile->platform=state;return true;}
void neo_platform_profile_destroy(neo_webview_profile_t* profile) noexcept {auto* state=static_cast<gtk_profile*>(profile->platform);if(!state)return;if(state->context)g_object_unref(state->context);delete state;profile->platform=nullptr;}
neo_webview_result_t neo_platform_profile_get_cookies(neo_webview_profile_t* profile,const std::string& uri,neo_webview_buffer_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {auto* state=static_cast<gtk_profile*>(profile->platform);if(!state||!state->context)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WebKitGTK profile is not initialized");auto* completion=new(std::nothrow) cookie_context{callback,context,operation};if(!completion)return neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK cookie operation allocation failed");webkit_cookie_manager_get_cookies(webkit_web_context_get_cookie_manager(state->context),uri.c_str(),nullptr,cookies_finished,completion);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_profile_set_cookie(neo_webview_profile_t* profile,const neo_webview_cookie_t* value,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {auto* state=static_cast<gtk_profile*>(profile->platform);if(!state||!state->context)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WebKitGTK profile is not initialized");auto* cookie=make_cookie(value);auto* completion=new(std::nothrow) cookie_change_context{callback,context,operation,false};if(!cookie||!completion){if(cookie)soup_cookie_free(cookie);delete completion;return neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK cookie allocation failed");}webkit_cookie_manager_add_cookie(webkit_web_context_get_cookie_manager(state->context),cookie,nullptr,cookie_changed,completion);soup_cookie_free(cookie);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_profile_delete_cookie(neo_webview_profile_t* profile,const neo_webview_cookie_t* value,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {auto* state=static_cast<gtk_profile*>(profile->platform);if(!state||!state->context)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WebKitGTK profile is not initialized");auto* cookie=make_cookie(value);auto* completion=new(std::nothrow) cookie_change_context{callback,context,operation,true};if(!cookie||!completion){if(cookie)soup_cookie_free(cookie);delete completion;return neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK cookie allocation failed");}webkit_cookie_manager_delete_cookie(webkit_web_context_get_cookie_manager(state->context),cookie,nullptr,cookie_changed,completion);soup_cookie_free(cookie);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_profile_clear_data(neo_webview_profile_t* profile,neo_webview_data_kind_t kinds,int64_t start,int64_t end,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {auto* state=static_cast<gtk_profile*>(profile->platform);if(!state||!state->context)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WebKitGTK profile is not initialized");if(end!=INT64_MAX||(kinds!=NEO_WEBVIEW_DATA_ALL&&(kinds&(NEO_WEBVIEW_DATA_PERMISSIONS|NEO_WEBVIEW_DATA_DOWNLOAD_HISTORY))))return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_SUPPORTED,"WebKitGTK cannot clear the selected data kinds or bounded end time");WebKitWebsiteDataTypes types=static_cast<WebKitWebsiteDataTypes>(0);if(kinds==NEO_WEBVIEW_DATA_ALL)types=WEBKIT_WEBSITE_DATA_ALL;else{if(kinds&NEO_WEBVIEW_DATA_COOKIES)types=static_cast<WebKitWebsiteDataTypes>(types|WEBKIT_WEBSITE_DATA_COOKIES);if(kinds&NEO_WEBVIEW_DATA_CACHE)types=static_cast<WebKitWebsiteDataTypes>(types|WEBKIT_WEBSITE_DATA_MEMORY_CACHE|WEBKIT_WEBSITE_DATA_DISK_CACHE|WEBKIT_WEBSITE_DATA_DOM_CACHE);if(kinds&NEO_WEBVIEW_DATA_LOCAL_STORAGE)types=static_cast<WebKitWebsiteDataTypes>(types|WEBKIT_WEBSITE_DATA_LOCAL_STORAGE);if(kinds&NEO_WEBVIEW_DATA_INDEXED_DB)types=static_cast<WebKitWebsiteDataTypes>(types|WEBKIT_WEBSITE_DATA_INDEXEDDB_DATABASES);if(kinds&NEO_WEBVIEW_DATA_SERVICE_WORKERS)types=static_cast<WebKitWebsiteDataTypes>(types|WEBKIT_WEBSITE_DATA_SERVICE_WORKER_REGISTRATIONS);}const auto now=g_get_real_time()/1000;const auto timespan=start==INT64_MIN?0:std::max<int64_t>(0,now-start)*1000;auto* completion=new(std::nothrow) clear_context{callback,context,operation};if(!completion)return neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"WebKitGTK clear-data allocation failed");auto* manager=webkit_web_context_get_website_data_manager(state->context);webkit_website_data_manager_clear(manager,types,timespan,nullptr,clear_finished,completion);return NEO_WEBVIEW_OK;}
bool neo_platform_view_create_async(neo_webview_view_t* view,const neo_webview_view_options_t*,neo_platform_created_callback_t callback,void* context,neo_webview_error_t** error) noexcept {auto* environment=static_cast<gtk_environment*>(view->environment->platform);auto* profile=view->profile?static_cast<gtk_profile*>(view->profile->platform):nullptr;auto* web_context=profile?profile->context:environment?environment->context:nullptr;auto* parent=view_parent(view);if(!web_context||!parent){neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_STATE,"WebKitGTK context or parent is unavailable");return false;}auto* state=new(std::nothrow) gtk_view;if(!state)return false;state->content=webkit_user_content_manager_new();webkit_user_content_manager_register_script_message_handler(state->content,"neowebview");state->widget=GTK_WIDGET(g_object_new(WEBKIT_TYPE_WEB_VIEW,"web-context",web_context,"user-content-manager",state->content,nullptr));view->platform=state;state->load_changed=g_signal_connect(state->widget,"load-changed",G_CALLBACK(load_changed),view);state->load_failed=g_signal_connect(state->widget,"load-failed",G_CALLBACK(load_failed),view);g_signal_connect(state->widget,"decide-policy",G_CALLBACK(decide_policy),view);state->title_changed=g_signal_connect(state->widget,"notify::title",G_CALLBACK(title_changed),view);state->uri_changed=g_signal_connect(state->widget,"notify::uri",G_CALLBACK(uri_changed),view);state->message_received=g_signal_connect(state->content,"script-message-received::neowebview",G_CALLBACK(message_received),view);if(GTK_IS_CONTAINER(parent))gtk_container_add(GTK_CONTAINER(parent),state->widget);gtk_widget_show(state->widget);callback(context,nullptr);return true;}
void neo_platform_view_destroy(neo_webview_view_t* view) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state)return;for(auto& entry:state->scripts)webkit_user_script_unref(entry.second);if(state->widget)gtk_widget_destroy(state->widget);if(state->content)g_object_unref(state->content);delete state;view->platform=nullptr;}
neo_webview_result_t neo_platform_view_set_bounds(neo_webview_view_t* view) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;gtk_widget_set_size_request(state->widget,view->fill_parent?-1:view->bounds.width,view->fill_parent?-1:view->bounds.height);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_navigate(neo_webview_view_t* view,const std::string& uri,neo_webview_error_t**) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;webkit_web_view_load_uri(WEBKIT_WEB_VIEW(state->widget),uri.c_str());return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_navigate_request(neo_webview_view_t* view,const std::string& uri,const std::string& method,const std::string& headers,const uint8_t*,uint64_t body_length,neo_webview_error_t** error) noexcept {if(method=="GET"&&headers.empty()&&body_length==0)return neo_platform_view_navigate(view,uri,error);return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_SUPPORTED,"WebKitGTK 4.1 does not expose arbitrary-method top-level navigation");}
neo_webview_result_t neo_platform_view_load_html(neo_webview_view_t* view,const std::string& html,const std::string& base,neo_webview_error_t**) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;webkit_web_view_load_html(WEBKIT_WEB_VIEW(state->widget),html.c_str(),base.empty()?nullptr:base.c_str());return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_command(neo_webview_view_t* view,uint32_t command) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;auto* web=WEBKIT_WEB_VIEW(state->widget);switch(command){case 0:webkit_web_view_stop_loading(web);break;case 1:webkit_web_view_reload(web);break;case 2:webkit_web_view_reload_bypass_cache(web);break;case 3:webkit_web_view_go_back(web);break;case 4:webkit_web_view_go_forward(web);break;default:return NEO_WEBVIEW_ERROR_INVALID_ARGUMENT;}return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_evaluate(neo_webview_view_t* view,const std::string& script,neo_webview_string_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t**) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;auto* completion=new(std::nothrow) script_context{view,callback,context,operation};if(!completion)return NEO_WEBVIEW_ERROR_NATIVE_FAILURE;webkit_web_view_evaluate_javascript(WEBKIT_WEB_VIEW(state->widget),script.data(),script.size(),nullptr,nullptr,nullptr,script_finished,completion);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_add_script(neo_webview_view_t* view,const std::string& script,const neo_webview_script_options_t* options,neo_webview_string_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t**) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->content)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;if(options->isolated_world)return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;const auto frames=options->main_frame_only?WEBKIT_USER_CONTENT_INJECT_TOP_FRAME:WEBKIT_USER_CONTENT_INJECT_ALL_FRAMES;const auto time=options->injection_time==NEO_WEBVIEW_SCRIPT_DOCUMENT_END?WEBKIT_USER_SCRIPT_INJECT_AT_DOCUMENT_END:WEBKIT_USER_SCRIPT_INJECT_AT_DOCUMENT_START;auto* user_script=webkit_user_script_new(script.c_str(),frames,time,nullptr,nullptr);if(!user_script)return NEO_WEBVIEW_ERROR_NATIVE_FAILURE;const auto identifier=std::to_string(state->next_script++);state->scripts.emplace(identifier,user_script);webkit_user_content_manager_add_script(state->content,user_script);g_idle_add(script_added,new add_script_context{callback,context,operation,identifier});return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_remove_script(neo_webview_view_t* view,const std::string& identifier) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->content)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;auto found=state->scripts.find(identifier);if(found==state->scripts.end())return NEO_WEBVIEW_ERROR_INVALID_ARGUMENT;webkit_user_script_unref(found->second);state->scripts.erase(found);webkit_user_content_manager_remove_all_scripts(state->content);for(const auto& entry:state->scripts)webkit_user_content_manager_add_script(state->content,entry.second);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_post_message(neo_webview_view_t* view,const std::string& message,bool json,neo_webview_error_t**) noexcept {auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;std::string script="window.dispatchEvent(new CustomEvent('neowebviewmessage',{detail:"+(json?message:("JSON.parse("+message+")"))+"}));";webkit_web_view_evaluate_javascript(WEBKIT_WEB_VIEW(state->widget),script.data(),script.size(),nullptr,nullptr,nullptr,nullptr,nullptr);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_get_handle(neo_webview_view_t* view,neo_webview_native_handle_kind_t kind,neo_webview_native_handle_t* handle) noexcept {if(kind!=NEO_WEBVIEW_NATIVE_HANDLE_WEBKITGTK_WEBVIEW&&kind!=NEO_WEBVIEW_NATIVE_HANDLE_GTK_WIDGET)return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;auto* state=static_cast<gtk_view*>(view->platform);if(!state||!state->widget)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;handle->kind=kind;handle->value=state->widget;return NEO_WEBVIEW_OK;}
