<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <Description>Optional Generic Host integration for NeoAstra.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/xoofx/NeoAstra</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NeoAstra\NeoAstra.csproj" />
    <ProjectReference Include="..\NeoAstra.Rpc\NeoAstra.Rpc.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="MinVer" PrivateAssets="all" />
    <None Include="$(MSBuildThisFileDirectory)../../readme.md" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)../../license.txt" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)../../doc/application-lifecycle-and-hosting.md" Pack="true" PackagePath="docs/" />
  </ItemGroup>
</Project>
