// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.

using CppAst.CodeGen.Common;
using CppAst.CodeGen.CSharp;
using ClangSharp.Interop;
using System.Runtime.InteropServices;
using Zio;
using Zio.FileSystems;

var repositoryRoot = FindRepositoryRoot(AppContext.BaseDirectory);
var header = Path.Combine(repositoryRoot, "native", "include", "neoastra.h");
var solution = Path.Combine(repositoryRoot, "src", "NeoAstra.slnx");
var outputDirectory = Path.Combine(repositoryRoot, "src", "NeoAstra.Core", "Generated", "Interop");

ConfigureLibClang();

if (!File.Exists(header) || !File.Exists(solution))
{
    Console.Error.WriteLine("Repository validation failed: expected native/include/neoastra.h and src/NeoAstra.slnx.");
    return 2;
}

var options = new CSharpConverterOptions
{
    DefaultNamespace = "NeoAstra.Interop.Generated",
    DefaultClassLib = "NativeMethods",
    DefaultDllImportNameAndArguments = "NativeMethods.LibraryName",
    DefaultOutputFilePath = "/NativeMethods.Generated.cs",
    DefaultOutputExtension = ".Generated.cs",
    GenerateAsInternal = true,
    GenerateEnumItemAsFields = false,
    UseLibraryImport = true,
    DisableRuntimeMarshalling = true,
    AllowMarshalForString = false,
    EnableAutoByRef = false,
    DetectOpaquePointers = true,
    MapVoidPtrToIntPtr = false,
};
options.IncludeFolders.Add(Path.GetDirectoryName(header)!);
options.AdditionalArguments.Add("-std=c++20");
options.AdditionalArguments.Add("-DNEOASTRA_BUILD=1");

var compilation = CSharpConverter.Convert([header], options);
if (compilation is null)
{
    Console.Error.WriteLine("CppAst.CodeGen returned no compilation.");
    return 3;
}

foreach (var diagnostic in compilation.Diagnostics.Messages)
{
    Console.Error.WriteLine(diagnostic);
}
if (compilation.HasErrors)
{
    return 4;
}

var memory = new MemoryFileSystem();
var writer = new CodeWriter(new CodeWriterOptions(memory) { NewLine = "\n" });
compilation.DumpTo(writer);

Directory.CreateDirectory(outputDirectory);
foreach (var stale in Directory.EnumerateFiles(outputDirectory, "*.Generated.cs", SearchOption.AllDirectories))
{
    File.Delete(stale);
}

const string license = "// Copyright (c) Alexandre Mutel. All rights reserved.\n// Licensed under the BSD-Clause 2 license.\n// <auto-generated>DO NOT EDIT. Run NeoAstra.CodeGen.</auto-generated>\n#pragma warning disable CS8909 // Generated function-pointer value equality is intentional.\n\n";
foreach (var path in memory.EnumerateFiles(UPath.Root, "*", SearchOption.AllDirectories).OrderBy(x => x.FullName, StringComparer.Ordinal))
{
    var relative = path.FullName.TrimStart('/').Replace('/', Path.DirectorySeparatorChar);
    var destination = Path.Combine(outputDirectory, relative);
    Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
    var generated = memory.ReadAllText(path).TrimStart('\uFEFF').Replace("\r\n", "\n", StringComparison.Ordinal).Replace("\r", "\n", StringComparison.Ordinal);
    generated = string.Join('\n', generated.Split('\n').Select(static line => line.TrimEnd()));
    File.WriteAllText(destination, license + generated, new System.Text.UTF8Encoding(false));
    Console.WriteLine(Path.GetRelativePath(repositoryRoot, destination).Replace('\\', '/'));
}
return 0;

static string FindRepositoryRoot(string start)
{
    var directory = new DirectoryInfo(start);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "src", "NeoAstra.slnx")) &&
            File.Exists(Path.Combine(directory.FullName, "native", "include", "neoastra.h")))
        {
            return directory.FullName;
        }
        directory = directory.Parent;
    }
    throw new InvalidOperationException("Could not locate the NeoAstra repository root.");
}

static void ConfigureLibClang()
{
    var configured = Environment.GetEnvironmentVariable("LIBCLANG_PATH");
    var candidates = new List<string>();
    if (!string.IsNullOrWhiteSpace(configured)) candidates.Add(configured);
    foreach (var directory in (Environment.GetEnvironmentVariable("PATH") ?? string.Empty).Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
    {
        candidates.Add(Path.Combine(directory.Trim('"'), OperatingSystem.IsWindows() ? "libclang.dll" : OperatingSystem.IsMacOS() ? "libclang.dylib" : "libclang.so"));
    }
    var libClang = candidates.FirstOrDefault(File.Exists);
    if (libClang is null)
    {
        throw new InvalidOperationException("libclang was not found. Install Clang and add its bin directory to PATH, or set LIBCLANG_PATH to the library file.");
    }
    clang.ResolveLibrary += (name, assembly, searchPath) =>
        name == "libclang" ? NativeLibrary.Load(libClang) : IntPtr.Zero;
}
