#include "../common/native_internal.hpp"

#import <Cocoa/Cocoa.h>
#import <WebKit/WebKit.h>
#import <dispatch/dispatch.h>

#include <algorithm>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace {
struct cocoa_app { };
struct cocoa_window;
struct cocoa_environment { WKProcessPool* process_pool; WKWebsiteDataStore* data_store; };
struct cocoa_profile { WKWebsiteDataStore* data_store; };
struct cocoa_view;

NSString* ns_string(const std::string& value) { return [[NSString alloc] initWithBytes:value.data() length:value.size() encoding:NSUTF8StringEncoding]; }
std::string utf8(NSString* value) { if(!value)return {};const char* text=value.UTF8String;return text?text:""; }
neo_webview_error_t* make_error(neo_webview_result_t code,const char* message,int64_t native_code=0,const char* domain="wkwebview") noexcept {neo_webview_error_t* error{};neo_fail(&error,code,message,native_code,domain);return error;}
}

@interface NeoWindowDelegate : NSObject<NSWindowDelegate>
@property(nonatomic,assign) neo_webview_window_t* nativeWindow;
@end
@interface NeoWebViewDelegate : NSObject<WKNavigationDelegate,WKScriptMessageHandler>
@property(nonatomic,assign) neo_webview_view_t* nativeView;
@end

namespace {
struct cocoa_window { NSWindow* window; NeoWindowDelegate* delegate; neo_webview_window_state_t reported_state{NEO_WEBVIEW_WINDOW_NORMAL}; };
struct cocoa_view { WKWebView* webview; NeoWebViewDelegate* delegate; std::unordered_map<std::string,WKUserScript*> scripts; };

struct navigation_context { void (^handler)(WKNavigationActionPolicy); };
void navigation_decided(void* pointer,neo_webview_decision_action_t action) noexcept {std::unique_ptr<navigation_context> context(static_cast<navigation_context*>(pointer));context->handler(action==NEO_WEBVIEW_DECISION_ALLOW?WKNavigationActionPolicyAllow:WKNavigationActionPolicyCancel);}
void report_window_state(neo_webview_window_t* value,neo_webview_window_state_t state){auto* native=static_cast<cocoa_window*>(value->platform);if(!native||native->reported_state==state)return;native->reported_state=state;{std::lock_guard lock(value->state_mutex);value->state=state;}neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_STATE_CHANGED,value->id,nullptr,nullptr,state);}
}

@implementation NeoWindowDelegate
- (BOOL)windowShouldClose:(NSWindow*)sender { (void)sender;auto* value=self.nativeWindow;if(value)neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_CLOSE_REQUESTED,value->id);return YES; }
- (void)windowWillClose:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value){auto* state=static_cast<cocoa_window*>(value->platform);if(state)state->window=nil;neo_window_closed(value);} }
- (void)windowDidResize:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(!value)return;NSWindow* window=static_cast<cocoa_window*>(value->platform)->window;NSRect frame=[window contentRectForFrameRect:window.frame];{std::lock_guard lock(value->state_mutex);value->bounds.width=(int32_t)frame.size.width;value->bounds.height=(int32_t)frame.size.height;}neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_RESIZED,value->id);if((window.styleMask&NSWindowStyleMaskFullScreen)!=0)report_window_state(value,NEO_WEBVIEW_WINDOW_FULLSCREEN);else if(window.miniaturized)report_window_state(value,NEO_WEBVIEW_WINDOW_MINIMIZED);else report_window_state(value,window.zoomed?NEO_WEBVIEW_WINDOW_MAXIMIZED:NEO_WEBVIEW_WINDOW_NORMAL); }
- (void)windowDidMove:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_MOVED,value->id); }
- (void)windowDidBecomeKey:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_FOCUS_CHANGED,value->id,nullptr,nullptr,1); }
- (void)windowDidResignKey:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)neo_emit_app(value->app,NEO_WEBVIEW_EVENT_WINDOW_FOCUS_CHANGED,value->id,nullptr,nullptr,0); }
- (void)windowDidMiniaturize:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)report_window_state(value,NEO_WEBVIEW_WINDOW_MINIMIZED); }
- (void)windowDidDeminiaturize:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)report_window_state(value,NEO_WEBVIEW_WINDOW_NORMAL); }
- (void)windowDidEnterFullScreen:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)report_window_state(value,NEO_WEBVIEW_WINDOW_FULLSCREEN); }
- (void)windowDidExitFullScreen:(NSNotification*)notification { (void)notification;auto* value=self.nativeWindow;if(value)report_window_state(value,NEO_WEBVIEW_WINDOW_NORMAL); }
@end

@implementation NeoWebViewDelegate
- (void)webView:(WKWebView*)webView decidePolicyForNavigationAction:(WKNavigationAction*)action decisionHandler:(void (^)(WKNavigationActionPolicy))handler {
    auto* view=self.nativeView;if(!view){handler(WKNavigationActionPolicyCancel);return;}std::string uri=utf8(action.request.URL.absoluteString);
    auto* decision=new neo_webview_decision;decision->kind=NEO_WEBVIEW_DECISION_NAVIGATION;decision->default_action=NEO_WEBVIEW_DECISION_ALLOW;
    decision->completion=navigation_decided;decision->completion_context=new navigation_context{[handler copy]};
    uint64_t flags=1u|(action.navigationType==WKNavigationTypeLinkActivated?2u:0u);neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_REQUESTED,0,nullptr,&uri,flags,0,decision);
    if(decision->state.load()==neo_decision_state::pending){neo_webview_decision_response_t response{sizeof(response),1,NEO_WEBVIEW_DECISION_DEFAULT};neo_webview_decision_complete(decision,&response,nullptr);}decision->release();
}
- (void)webView:(WKWebView*)webView didStartProvisionalNavigation:(WKNavigation*)navigation { (void)navigation;auto* view=self.nativeView;if(!view)return;std::string uri=utf8(webView.URL.absoluteString);neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_STARTED,0,nullptr,&uri,1); }
- (void)webView:(WKWebView*)webView didFinishNavigation:(WKNavigation*)navigation { (void)navigation;auto* view=self.nativeView;if(!view)return;std::string uri=utf8(webView.URL.absoluteString);neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_COMPLETED,0,nullptr,&uri); }
- (void)webView:(WKWebView*)webView didFailNavigation:(WKNavigation*)navigation withError:(NSError*)error { (void)navigation;auto* view=self.nativeView;if(!view)return;std::string uri=utf8(webView.URL.absoluteString);neo_emit_view(view,NEO_WEBVIEW_EVENT_NAVIGATION_FAILED,0,nullptr,&uri,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,error.code); }
- (void)webView:(WKWebView*)webView didFailProvisionalNavigation:(WKNavigation*)navigation withError:(NSError*)error { [self webView:webView didFailNavigation:navigation withError:error]; }
- (void)userContentController:(WKUserContentController*)controller didReceiveScriptMessage:(WKScriptMessage*)message { (void)controller;auto* view=self.nativeView;if(!view)return;NSError* error=nil;NSData* data=[NSJSONSerialization dataWithJSONObject:message.body options:0 error:&error];std::string text;if(data&&!error)text.assign((const char*)data.bytes,data.length);else text=utf8([message.body description]);std::string uri=utf8(message.frameInfo.request.URL.absoluteString);neo_emit_view(view,NEO_WEBVIEW_EVENT_MESSAGE_RECEIVED,0,&text,&uri,data?1u:0u); }
- (void)observeValueForKeyPath:(NSString*)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id>*)change context:(void*)context { (void)change;(void)context;auto* view=self.nativeView;if(!view)return;WKWebView* webview=(WKWebView*)object;if([keyPath isEqualToString:@"title"]){view->title=utf8(webview.title);neo_emit_view(view,NEO_WEBVIEW_EVENT_TITLE_CHANGED,0,&view->title);}else if([keyPath isEqualToString:@"URL"]){view->source=utf8(webview.URL.absoluteString);neo_emit_view(view,NEO_WEBVIEW_EVENT_SOURCE_CHANGED,0,nullptr,&view->source);} }
@end

namespace {
NSView* view_parent(neo_webview_view_t* view) {if(view->window){auto* state=static_cast<cocoa_window*>(view->window->platform);return state?state->window.contentView:nil;}return view->parent.kind==NEO_WEBVIEW_NATIVE_PARENT_COCOA_NSVIEW?(__bridge NSView*)view->parent.handle:nil;}
NSRect view_frame(neo_webview_view_t* view,NSView* parent){if(view->fill_parent)return parent.bounds;return NSMakeRect(view->bounds.x,view->bounds.y,std::max(view->bounds.width,1),std::max(view->bounds.height,1));}
}

bool neo_platform_initialize(neo_webview_app_t* app,neo_webview_error_t**) noexcept {@autoreleasepool{[NSApplication sharedApplication];[NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];app->platform=new cocoa_app;return true;}}
void neo_platform_shutdown(neo_webview_app_t* app) noexcept {delete static_cast<cocoa_app*>(app->platform);app->platform=nullptr;}
int32_t neo_platform_run(neo_webview_app_t* app) noexcept {@autoreleasepool{[NSApp run];return app->exit_code.load();}}
void neo_platform_quit(neo_webview_app_t*) noexcept {dispatch_async(dispatch_get_main_queue(),^{[NSApp stop:nil];NSEvent* event=[NSEvent otherEventWithType:NSEventTypeApplicationDefined location:NSZeroPoint modifierFlags:0 timestamp:0 windowNumber:0 context:nil subtype:0 data1:0 data2:0];[NSApp postEvent:event atStart:NO];});}
void neo_platform_wake(neo_webview_app_t* app) noexcept {app->retain();dispatch_async(dispatch_get_main_queue(),^{neo_drain_dispatch(app);app->release();});}

bool neo_platform_window_create(neo_webview_window_t* window,const neo_webview_window_options_t* options,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=new cocoa_window{};window->platform=state;NSWindowStyleMask style=NSWindowStyleMaskClosable|NSWindowStyleMaskMiniaturizable;if(options->flags&2u)style|=NSWindowStyleMaskTitled;if(options->flags&1u)style|=NSWindowStyleMaskResizable;state->window=[[NSWindow alloc]initWithContentRect:NSMakeRect(window->bounds.x,window->bounds.y,window->bounds.width,window->bounds.height) styleMask:style backing:NSBackingStoreBuffered defer:NO];state->delegate=[NeoWindowDelegate new];state->delegate.nativeWindow=window;state->window.delegate=state->delegate;state->window.title=ns_string(window->title);state->window.releasedWhenClosed=NO;if(options->minimum_size.width>0||options->minimum_size.height>0)state->window.contentMinSize=NSMakeSize(std::max(options->minimum_size.width,0),std::max(options->minimum_size.height,0));if(options->maximum_size.width>0||options->maximum_size.height>0)state->window.contentMaxSize=NSMakeSize(options->maximum_size.width>0?options->maximum_size.width:CGFLOAT_MAX,options->maximum_size.height>0?options->maximum_size.height:CGFLOAT_MAX);if(options->flags&8u)state->window.level=NSFloatingWindowLevel;if(options->flags&4u){[state->window makeKeyAndOrderFront:nil];if(options->state==NEO_WEBVIEW_WINDOW_MINIMIZED)[state->window miniaturize:nil];else if(options->state==NEO_WEBVIEW_WINDOW_MAXIMIZED)[state->window zoom:nil];else if(options->state==NEO_WEBVIEW_WINDOW_FULLSCREEN)[state->window toggleFullScreen:nil];}[NSApp activateIgnoringOtherApps:YES];return true;}}
void neo_platform_window_destroy(neo_webview_window_t* window) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_window*>(window->platform);if(!state)return;state->delegate.nativeWindow=nullptr;state->window.delegate=nil;if(state->window)[state->window close];delete state;window->platform=nullptr;}}
neo_webview_result_t neo_platform_window_show(neo_webview_window_t* window,bool visible) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;if(!visible){[state->window orderOut:nil];return NEO_WEBVIEW_OK;}neo_webview_window_state_t desired{};{std::lock_guard lock(window->state_mutex);desired=window->state;}[state->window orderFront:nil];{std::lock_guard lock(window->state_mutex);window->state=desired;}return neo_platform_window_set_state(window);}
neo_webview_result_t neo_platform_window_activate(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;[state->window makeKeyAndOrderFront:nil];[NSApp activateIgnoringOtherApps:YES];return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_close(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;[state->window performClose:nil];return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_title(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;state->window.title=ns_string(window->title);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_bounds(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;[state->window setFrame:NSMakeRect(window->bounds.x,window->bounds.y,window->bounds.width,window->bounds.height) display:YES];return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_size_constraints(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;state->window.contentMinSize=NSMakeSize(std::max(window->minimum_size.width,0),std::max(window->minimum_size.height,0));state->window.contentMaxSize=NSMakeSize(window->maximum_size.width>0?window->maximum_size.width:CGFLOAT_MAX,window->maximum_size.height>0?window->maximum_size.height:CGFLOAT_MAX);return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_set_state(neo_webview_window_t* window) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;if(!state->window.visible&&(state->window.styleMask&NSWindowStyleMaskFullScreen)==0)return NEO_WEBVIEW_OK;switch(window->state){case NEO_WEBVIEW_WINDOW_NORMAL:if(state->window.miniaturized)[state->window deminiaturize:nil];if(state->window.zoomed)[state->window zoom:nil];if((state->window.styleMask&NSWindowStyleMaskFullScreen)!=0)[state->window toggleFullScreen:nil];break;case NEO_WEBVIEW_WINDOW_MINIMIZED:[state->window miniaturize:nil];break;case NEO_WEBVIEW_WINDOW_MAXIMIZED:if(!state->window.zoomed)[state->window zoom:nil];break;case NEO_WEBVIEW_WINDOW_FULLSCREEN:if((state->window.styleMask&NSWindowStyleMaskFullScreen)==0)[state->window toggleFullScreen:nil];break;default:return NEO_WEBVIEW_ERROR_INVALID_ARGUMENT;}return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_window_get_handle(neo_webview_window_t* window,neo_webview_native_handle_kind_t kind,neo_webview_native_handle_t* handle) noexcept {auto* state=static_cast<cocoa_window*>(window->platform);if(!state||!state->window)return NEO_WEBVIEW_ERROR_DISPOSED;if(kind==NEO_WEBVIEW_NATIVE_HANDLE_COCOA_NSWINDOW)handle->value=(__bridge void*)state->window;else if(kind==NEO_WEBVIEW_NATIVE_HANDLE_COCOA_NSVIEW)handle->value=(__bridge void*)state->window.contentView;else return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;handle->kind=kind;return NEO_WEBVIEW_OK;}

bool neo_platform_environment_create_async(neo_webview_environment_t* environment,const neo_webview_environment_options_t* options,neo_platform_created_callback_t callback,void* context,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=new cocoa_environment{};state->process_pool=[WKProcessPool new];state->data_store=options->private_mode?[WKWebsiteDataStore nonPersistentDataStore]:[WKWebsiteDataStore defaultDataStore];environment->platform=state;callback(context,nullptr);return true;}}
void neo_platform_environment_destroy(neo_webview_environment_t* environment) noexcept {delete static_cast<cocoa_environment*>(environment->platform);environment->platform=nullptr;}
bool neo_platform_profile_create(neo_webview_profile_t* profile,neo_webview_error_t** error) noexcept {@autoreleasepool{try{auto* state=new cocoa_profile{};state->data_store=profile->ephemeral?[WKWebsiteDataStore nonPersistentDataStore]:[WKWebsiteDataStore defaultDataStore];profile->platform=state;return true;}catch(...){neo_fail(error,NEO_WEBVIEW_ERROR_NATIVE_FAILURE,"Could not allocate WKWebView profile state");return false;}}}
void neo_platform_profile_destroy(neo_webview_profile_t* profile) noexcept {delete static_cast<cocoa_profile*>(profile->platform);profile->platform=nullptr;}
neo_webview_result_t neo_platform_profile_get_cookies(neo_webview_profile_t* profile,const std::string& uri,neo_webview_buffer_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_profile*>(profile->platform);NSURL* url=[NSURL URLWithString:ns_string(uri)];if(!state||!state->data_store||!url)return neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_ARGUMENT,"Invalid WKWebView cookie URI");[state->data_store.httpCookieStore getAllCookies:^(NSArray<NSHTTPCookie*>* values){@autoreleasepool{NSMutableArray* output=[NSMutableArray array];NSString* host=url.host.lowercaseString;NSString* request_path=url.path.length?url.path:@"/";for(NSHTTPCookie* cookie in values){NSString* domain=cookie.domain.lowercaseString;BOOL domain_match=[host isEqualToString:domain]||([domain hasPrefix:@"."]&&[host hasSuffix:domain]);BOOL path_match=[request_path hasPrefix:cookie.path.length?cookie.path:@"/"];if(!domain_match||!path_match||(cookie.secure&&![url.scheme.lowercaseString isEqualToString:@"https"]))continue;NSMutableDictionary* item=[@{@"name":cookie.name,@"value":cookie.value,@"domain":cookie.domain,@"path":cookie.path.length?cookie.path:@"/",@"secure":@(cookie.secure),@"httpOnly":@(cookie.HTTPOnly),@"sameSite":@0} mutableCopy];if(cookie.expiresDate)item[@"expiresUnixMs"]=@((int64_t)(cookie.expiresDate.timeIntervalSince1970*1000.0));[output addObject:item];}NSError* serialization_error=nil;NSData* data=[NSJSONSerialization dataWithJSONObject:output options:0 error:&serialization_error];neo_webview_result_t requested=serialization_error?NEO_WEBVIEW_ERROR_NATIVE_FAILURE:NEO_WEBVIEW_OK,actual{};neo_webview_error_t* native_error=serialization_error?make_error(requested,utf8(serialization_error.localizedDescription).c_str(),serialization_error.code):nullptr;auto* buffer=data?new neo_webview_buffer(std::vector<uint8_t>((const uint8_t*)data.bytes,(const uint8_t*)data.bytes+data.length)):nullptr;if(operation->try_complete(requested,actual)){callback(context,actual,actual==NEO_WEBVIEW_OK?buffer:nullptr,actual==requested?native_error:nullptr);if(actual!=NEO_WEBVIEW_OK&&buffer)buffer->release();}else if(buffer)buffer->release();if(native_error)native_error->release();operation->release();}}];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_profile_set_cookie(neo_webview_profile_t* profile,const neo_webview_cookie_t* cookie,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_profile*>(profile->platform);if(!state||!state->data_store)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WKWebView profile is not initialized");NSMutableDictionary* properties=[@{NSHTTPCookieName:ns_string(neo_string(cookie->name)),NSHTTPCookieValue:ns_string(neo_string(cookie->value)),NSHTTPCookieDomain:ns_string(neo_string(cookie->domain)),NSHTTPCookiePath:ns_string(neo_string(cookie->path))} mutableCopy];if(cookie->flags&1u)properties[NSHTTPCookieSecure]=@"TRUE";if(cookie->flags&2u)properties[@"HttpOnly"]=@"TRUE";if((cookie->flags&4u)==0&&cookie->expires_unix_ms>0)properties[NSHTTPCookieExpires]=[NSDate dateWithTimeIntervalSince1970:cookie->expires_unix_ms/1000.0];NSHTTPCookie* value=[NSHTTPCookie cookieWithProperties:properties];if(!value)return neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_ARGUMENT,"Invalid WKWebView cookie");[state->data_store.httpCookieStore setCookie:value completionHandler:^{neo_webview_result_t actual{};if(operation->try_complete(NEO_WEBVIEW_OK,actual))callback(context,actual,nullptr);operation->release();}];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_profile_delete_cookie(neo_webview_profile_t* profile,const neo_webview_cookie_t* cookie,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_profile*>(profile->platform);if(!state||!state->data_store)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WKWebView profile is not initialized");NSDictionary* properties=@{NSHTTPCookieName:ns_string(neo_string(cookie->name)),NSHTTPCookieValue:ns_string(neo_string(cookie->value)),NSHTTPCookieDomain:ns_string(neo_string(cookie->domain)),NSHTTPCookiePath:ns_string(neo_string(cookie->path))};NSHTTPCookie* value=[NSHTTPCookie cookieWithProperties:properties];if(!value)return neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_ARGUMENT,"Invalid WKWebView cookie");[state->data_store.httpCookieStore deleteCookie:value completionHandler:^{neo_webview_result_t actual{};if(operation->try_complete(NEO_WEBVIEW_OK,actual))callback(context,actual,nullptr);operation->release();}];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_profile_clear_data(neo_webview_profile_t* profile,neo_webview_data_kind_t kinds,int64_t start,int64_t end,neo_webview_completion_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_profile*>(profile->platform);if(!state||!state->data_store)return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_INITIALIZED,"WKWebView profile is not initialized");if(end!=INT64_MAX||(kinds!=NEO_WEBVIEW_DATA_ALL&&(kinds&(NEO_WEBVIEW_DATA_SERVICE_WORKERS|NEO_WEBVIEW_DATA_PERMISSIONS|NEO_WEBVIEW_DATA_DOWNLOAD_HISTORY))))return neo_fail(error,NEO_WEBVIEW_ERROR_NOT_SUPPORTED,"WKWebView cannot clear the selected data kinds or bounded end time");NSMutableSet<NSString*>* types=[NSMutableSet set];if(kinds==NEO_WEBVIEW_DATA_ALL)[types unionSet:[WKWebsiteDataStore allWebsiteDataTypes]];else{if(kinds&NEO_WEBVIEW_DATA_COOKIES)[types addObject:WKWebsiteDataTypeCookies];if(kinds&NEO_WEBVIEW_DATA_CACHE){[types addObject:WKWebsiteDataTypeDiskCache];[types addObject:WKWebsiteDataTypeMemoryCache];}if(kinds&NEO_WEBVIEW_DATA_LOCAL_STORAGE)[types addObject:WKWebsiteDataTypeLocalStorage];if(kinds&NEO_WEBVIEW_DATA_INDEXED_DB)[types addObject:WKWebsiteDataTypeIndexedDBDatabases];}NSDate* since=start==INT64_MIN?[NSDate distantPast]:[NSDate dateWithTimeIntervalSince1970:start/1000.0];[state->data_store removeDataOfTypes:types modifiedSince:since completionHandler:^{neo_webview_result_t actual{};if(operation->try_complete(NEO_WEBVIEW_OK,actual))callback(context,actual,nullptr);operation->release();}];return NEO_WEBVIEW_OK;}}
bool neo_platform_view_create_async(neo_webview_view_t* view,const neo_webview_view_options_t*,neo_platform_created_callback_t callback,void* context,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* environment=static_cast<cocoa_environment*>(view->environment->platform);NSView* parent=view_parent(view);if(!environment||!parent){neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_STATE,"WKWebView environment or parent is unavailable");return false;}auto* state=new cocoa_view{};WKWebViewConfiguration* configuration=[WKWebViewConfiguration new];configuration.processPool=environment->process_pool;auto* profile=view->profile?static_cast<cocoa_profile*>(view->profile->platform):nullptr;configuration.websiteDataStore=profile?profile->data_store:environment->data_store;state->delegate=[NeoWebViewDelegate new];state->delegate.nativeView=view;[configuration.userContentController addScriptMessageHandler:state->delegate name:@"neowebview"];state->webview=[[WKWebView alloc]initWithFrame:view_frame(view,parent) configuration:configuration];state->webview.navigationDelegate=state->delegate;if(view->fill_parent)state->webview.autoresizingMask=NSViewWidthSizable|NSViewHeightSizable;[parent addSubview:state->webview];view->platform=state;[state->webview addObserver:state->delegate forKeyPath:@"title" options:NSKeyValueObservingOptionNew context:nullptr];[state->webview addObserver:state->delegate forKeyPath:@"URL" options:NSKeyValueObservingOptionNew context:nullptr];callback(context,nullptr);return true;}}
void neo_platform_view_destroy(neo_webview_view_t* view) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state)return;@try{[state->webview removeObserver:state->delegate forKeyPath:@"title"];[state->webview removeObserver:state->delegate forKeyPath:@"URL"];}@catch(NSException*){}state->delegate.nativeView=nullptr;state->webview.navigationDelegate=nil;[state->webview.configuration.userContentController removeScriptMessageHandlerForName:@"neowebview"];[state->webview removeFromSuperview];delete state;view->platform=nullptr;}}
neo_webview_result_t neo_platform_view_set_bounds(neo_webview_view_t* view) noexcept {auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;NSView* parent=view_parent(view);state->webview.frame=view_frame(view,parent);state->webview.autoresizingMask=view->fill_parent?(NSViewWidthSizable|NSViewHeightSizable):NSViewNotSizable;return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_navigate(neo_webview_view_t* view,const std::string& uri,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);NSURL* url=[NSURL URLWithString:ns_string(uri)];if(!state||!state->webview||!url)return neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_ARGUMENT,"Invalid WKWebView navigation URI");[state->webview loadRequest:[NSURLRequest requestWithURL:url]];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_navigate_request(neo_webview_view_t* view,const std::string& uri,const std::string& method,const std::string& headers,const uint8_t* body,uint64_t body_length,neo_webview_error_t** error) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);NSURL* url=[NSURL URLWithString:ns_string(uri)];if(!state||!state->webview||!url||method.empty()||body_length>NSUIntegerMax)return neo_fail(error,NEO_WEBVIEW_ERROR_INVALID_ARGUMENT,"Invalid WKWebView navigation request");NSMutableURLRequest* request=[NSMutableURLRequest requestWithURL:url];request.HTTPMethod=ns_string(method);if(body_length)request.HTTPBody=[NSData dataWithBytes:body length:(NSUInteger)body_length];for(NSString* line in [ns_string(headers) componentsSeparatedByCharactersInSet:[NSCharacterSet newlineCharacterSet]]){NSRange separator=[line rangeOfString:@":"];if(separator.location==NSNotFound)continue;NSString* name=[[line substringToIndex:separator.location] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];NSString* value=[[line substringFromIndex:separator.location+1] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];if(name.length)[request setValue:value forHTTPHeaderField:name];}[state->webview loadRequest:request];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_load_html(neo_webview_view_t* view,const std::string& html,const std::string& base,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;NSURL* url=base.empty()?nil:[NSURL URLWithString:ns_string(base)];[state->webview loadHTMLString:ns_string(html) baseURL:url];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_command(neo_webview_view_t* view,uint32_t command) noexcept {auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;switch(command){case 0:[state->webview stopLoading];break;case 1:case 2:[state->webview reload];break;case 3:[state->webview goBack];break;case 4:[state->webview goForward];break;default:return NEO_WEBVIEW_ERROR_INVALID_ARGUMENT;}return NEO_WEBVIEW_OK;}
neo_webview_result_t neo_platform_view_evaluate(neo_webview_view_t* view,const std::string& script,neo_webview_string_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;[state->webview evaluateJavaScript:ns_string(script) completionHandler:^(id value,NSError* error){neo_webview_result_t requested=error?NEO_WEBVIEW_ERROR_NATIVE_FAILURE:NEO_WEBVIEW_OK,actual{};neo_webview_error_t* native_error=error?make_error(requested,utf8(error.localizedDescription).c_str(),error.code):nullptr;std::string output="null";if(value){NSData* data=[NSJSONSerialization dataWithJSONObject:value options:NSJSONWritingFragmentsAllowed error:nil];if(data)output.assign((const char*)data.bytes,data.length);}if(operation->try_complete(requested,actual))callback(context,actual,actual==NEO_WEBVIEW_OK?neo_string_view(output):neo_webview_string_view_t{},native_error);if(native_error)native_error->release();operation->release();}];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_add_script(neo_webview_view_t* view,const std::string& script,const neo_webview_script_options_t* options,neo_webview_string_callback_t callback,void* context,neo_webview_operation_t* operation,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;if(options->isolated_world)return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;auto time=options->injection_time==NEO_WEBVIEW_SCRIPT_DOCUMENT_END?WKUserScriptInjectionTimeAtDocumentEnd:WKUserScriptInjectionTimeAtDocumentStart;WKUserScript* user_script=[[WKUserScript alloc]initWithSource:ns_string(script) injectionTime:time forMainFrameOnly:options->main_frame_only!=0];std::string identifier=utf8([NSUUID UUID].UUIDString);state->scripts.emplace(identifier,user_script);[state->webview.configuration.userContentController addUserScript:user_script];dispatch_async(dispatch_get_main_queue(),^{neo_webview_result_t actual{};if(operation->try_complete(NEO_WEBVIEW_OK,actual))callback(context,actual,actual==NEO_WEBVIEW_OK?neo_string_view(identifier):neo_webview_string_view_t{},nullptr);operation->release();});return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_remove_script(neo_webview_view_t* view,const std::string& identifier) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;auto found=state->scripts.find(identifier);if(found==state->scripts.end())return NEO_WEBVIEW_ERROR_INVALID_ARGUMENT;state->scripts.erase(found);auto* manager=state->webview.configuration.userContentController;[manager removeAllUserScripts];for(const auto& entry:state->scripts)[manager addUserScript:entry.second];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_post_message(neo_webview_view_t* view,const std::string& message,bool json,neo_webview_error_t**) noexcept {@autoreleasepool{auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;std::string script="window.dispatchEvent(new CustomEvent('neowebviewmessage',{detail:"+(json?message:"null")+"}));";[state->webview evaluateJavaScript:ns_string(script) completionHandler:nil];return NEO_WEBVIEW_OK;}}
neo_webview_result_t neo_platform_view_get_handle(neo_webview_view_t* view,neo_webview_native_handle_kind_t kind,neo_webview_native_handle_t* handle) noexcept {if(kind!=NEO_WEBVIEW_NATIVE_HANDLE_WKWEBVIEW&&kind!=NEO_WEBVIEW_NATIVE_HANDLE_COCOA_NSVIEW)return NEO_WEBVIEW_ERROR_NOT_SUPPORTED;auto* state=static_cast<cocoa_view*>(view->platform);if(!state||!state->webview)return NEO_WEBVIEW_ERROR_NOT_INITIALIZED;handle->kind=kind;handle->value=(__bridge void*)state->webview;return NEO_WEBVIEW_OK;}
